name: Auto Job Application

on:
  push:
    branches: [ main ]  # You can change this to your branch name
  workflow_dispatch:    # Allows manual run from GitHub UI

jobs:
  run-auto-job-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping dependency installation."
          fi

      - name: Run Auto Job Application Script
        run: python auto_apply.py
